package com.paranoid.euler
/** Each new term in the Fibonacci sequence is generated by adding the 
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 */
object Problem002 extends App {
  println("Result (O(n)): " + sumEvenFibo(4000000))
//  println("Checking with brute force (O(n)): " + bruteForceCheck(1000, 3, 5))

  def sumEvenFibo(limit: Int): Int = {
    var sum = 0
    var current = 2
    var last = 1
    while (current < limit) {
      if (current % 2 == 0)
        sum += current
      var next = current + last
      last = current
      current = next
    }
    return sum
  }

}